export const campaigns = [
  {
    id: 1,
    name: "SW Zero Personalisation 1",
    status: "Sent",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 30,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 2,
    name: "Untitled Campaign",
    status: "Drafted",
    date: "13 Apr 2023",
    sequences: "5 Sequences",
    progress: 0,
    metrics: {
      sent: 0,
      clicked: { value: 0, percentage: 0.0 },
      opened: { value: 0, percentage: 0.0 },
      replied: { value: 0, percentage: 0.0 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 3,
    name: "SW Zero Personalisation 1",
    status: "Sent",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 30,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 4,
    name: "SW Zero Personalisation 1",
    status: "Stopped",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 0,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 5,
    name: "SW Zero Personalisation 1",
    status: "Sent",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 30,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 6,
    name: "Untitled Campaign",
    status: "Drafted",
    date: "13 Apr 2023",
    sequences: "5 Sequences",
    progress: 0,
    metrics: {
      sent: 0,
      clicked: { value: 0, percentage: 0.0 },
      opened: { value: 0, percentage: 0.0 },
      replied: { value: 0, percentage: 0.0 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 7,
    name: "SW Zero Personalisation 1",
    status: "Paused",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 30,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
  {
    id: 8,
    name: "SW Zero Personalisation 1",
    status: "Sent",
    date: "15 Apr 2023",
    sequences: "3 Sequences",
    progress: 30,
    metrics: {
      sent: 520,
      clicked: { value: 39, percentage: 19.6 },
      opened: { value: 202, percentage: 39.8 },
      replied: { value: 4, percentage: 12.4 },
      positive: { value: 0, percentage: 0.0 },
    },
  },
];

export const getCampaigns = () => {
  return [...campaigns, ...campaigns, ...campaigns];
};
